#!/bin/sh
echo ""
echo "🧠 Conventional Commit Format:"
echo "  type(scope?): subject"
echo ""
echo "✅ Valid types:"
echo "  feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
echo ""
npx --no -- commitlint --edit "$1"
